spring:
  application:
    name: reservation-service
  profiles:
    active: dev
  config:
    import:
      - optional:configserver:http://admin:admin777@localhost:8888
  cloud:
    config:
      name: reservation-service,reservation-service-db